# Project: pekko pekko
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = pekko_private.res
OBJ  = main.o tela.o fundo.o pacman.o jogo.o teclado.o fantasma.o astar.o $(RES)
LINKOBJ  = main.o tela.o fundo.o pacman.o jogo.o teclado.o fantasma.o astar.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows -lalleg 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = pekko.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before pekko.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "pekko.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

tela.o: tela.c
	$(CC) -c tela.c -o tela.o $(CFLAGS)

fundo.o: fundo.c
	$(CC) -c fundo.c -o fundo.o $(CFLAGS)

pacman.o: pacman.c
	$(CC) -c pacman.c -o pacman.o $(CFLAGS)

jogo.o: jogo.c
	$(CC) -c jogo.c -o jogo.o $(CFLAGS)

teclado.o: teclado.c
	$(CC) -c teclado.c -o teclado.o $(CFLAGS)

fantasma.o: fantasma.c
	$(CC) -c fantasma.c -o fantasma.o $(CFLAGS)

astar.o: astar.c
	$(CC) -c astar.c -o astar.o $(CFLAGS)

pekko_private.res: pekko_private.rc 
	$(WINDRES) -i pekko_private.rc --input-format=rc -o pekko_private.res -O coff 
